### ISSUE TITLE
Unable to install endaga in osmocom client

### ISSUE THREAD

**Issue by mvillanoy** [pcarivbts/CommunityCellularManager#8]
vagrant@endaga-client-osmocom:~/endaga-packages$ sudo apt-get install endaga-osmocom
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 endaga-osmocom : Depends: openggsn (>= 0.92) but it is not installable
                  Depends: osmocom-sgsn (>= 0.15.0) but it is not installable
                  Depends: freeswitch-meta-vanilla but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by eprueves** [comment]
Also documented in
https://github.com/facebookincubator/CommunityCellularManager/issues/89

**Comment by eprueves** [comment]
@mkmvillanoy Here's a quick workaround:

- install fpm
- in client/packaging, there's a file named 'build-endaga.sh'
- edit lines 88 & 93
- replace package names with osmo-ggsn and osmo-sgsn . Omit the version numbers, I don't know what to put yet. 
- run the script: `./build-endaga.sh /tmp osmocom`. This will generate a deb file in the /tmp directory
- install using gdebi: `sudo gdebi endaga-osmocom_0.8.1_all.deb`
